# REQUIRED
name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}

# OPTIONAL
author: Packet
description: Required platform plugin
load: STARTUP